name: trusted CI container build

on:
  push

jobs:
  image-for-trusted-ci:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@master

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: ghcr.io/parsl/trusted-ci:ci
        push: true

